### ISSUE TITLE
attempt to multiply with overflow with hdr.record_size in read_one_shape_as

### ISSUE THREAD

**Issue by oumnaya** [tmontaigu/shapefile-rs#25]
Hello,

I am a beginner in rust and shape file in general.

When i open shape, shapefile panic : 
`'main' panicked at 'attempt to multiply with overflow', ...shapefile-0.3.0\src\reader.rs:107:23.`

My code (simplify) :
```
fn open_shape(filename: String) -> Vec<(shapefile::Shape, dbase::Record)>{
    let mut reader;
    match shapefile::Reader::from_path(filename.to_string()){
        Ok(x) => reader = x,
        Err(shapefile::Error::MissingDbf) => exit(2),
        _ => exit(3)
    };
    match reader.read() {
        Ok(data_shape) => return data_shape,
        Err(e) => exit(4)
    }   
}
```
     
When i debug i see this : 

panic in reader.read() in read_one_shape_as 
this line : reader.rs 107 : `let record_size = hdr.record_size * 2;`
`hdr.record_size =  -1409209791`

I don't if my shape have a problem or if it's an error not properly catch by the library.
i have no problem to open my shape in qgis

**Comment by tmontaigu** [comment]
Hello, are you able to share the file ?

**Comment by hb-axec** [comment]
Sorry for the late response, do you have an email or a place where i can send a link wetransfert ? (the file is from my work i prefer send to you directly) (it's oumnaya this account is my pro-account)

**Comment by tmontaigu** [comment]
yes you can send the link to `yoshi1189@hotmail.fr`

**Comment by tmontaigu** [comment]
Ok so I had a quick look at the file and the behavior of shapefile-rs:

`shapefile-rs` reads the shapes from `.shp`  sequentially when you use a `iter_*` function.

However in your file it seems that there are garbage bytes between two `shapes` and since we don't skip them, we read them interpret them and boom overflow when multiplying in debug build and other problem in release build.

Fixing this will require a bit of 'engineering'.

In the meantime you should be able to read the file successfully by doing 
```Rust
use shapefile;
use shapefile::dbase;

fn main() {
    let mut shape_reader = shapefile::ShapeReader::from_path(filename).unwrap();
    let mut dbase_reader = dbase::Reader::from_path(filename).unwrap();
    let mut record_iterator = dbase_reader.iter_records();

    let shape_count = shape_reader.shape_count().unwrap();
    for i in 0..shape_count {
        let result = shape_reader.read_nth_shape(i);
        let shape = result.unwrap().unwrap();
        let record = record_iterator.next().unwrap().unwrap();
        println!("{} / {}", i + 1, shape_count);
        println!("Shape: {}", shape);
        println!("Record {:?}", record);
    }
}
```

You can see that we use `shape_reader.read_nth_shape(i)` because this function actually seeks to the proper start of the shape by using the offsets stored in the `shx` file and that skips garbage bytes if there are any.
